Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  3.16.460.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Constituent Summary Event Registrations Tile View Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "60162969-88e0-4978-813a-f629c93ea679", "836843d3-6380-48e0-8bd5-2477cc117f30", "Constituent")>
Partial Public Class [ConstituentSummaryEventRegistrationsTileViewFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _registrations As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentSummaryEventRegistrationsTileViewFormREGISTRATIONSUIModel)
    Private WithEvents _currentregistrantindex As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _startdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _type As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _status As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _registration As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _registrationcounttext As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _currentregistrantid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _noregistrations As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _headerlink As Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction
    Private WithEvents _eventname As Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction
    Private WithEvents _nextregistration As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _previousregistration As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public Sub New()
        MyBase.New()

        _registrations = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentSummaryEventRegistrationsTileViewFormREGISTRATIONSUIModel)
        _currentregistrantindex = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _startdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _type = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _status = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _registration = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _registrationcounttext = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _currentregistrantid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _noregistrations = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _headerlink = New Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction
        _eventname = New Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction
        _nextregistration = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _previousregistration = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New System.Guid("60162969-88e0-4978-813a-f629c93ea679")
        MyBase.DataFormInstanceId = New System.Guid("836843d3-6380-48e0-8bd5-2477cc117f30")
        MyBase.RecordType = "Constituent"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.eventstile/ConstituentSummaryEventRegistrationsTileViewForm.html"

        '
        '_registrations
        '
        _registrations.Name = "REGISTRATIONS"
        _registrations.Caption = "REGISTRATIONS"
        _registrations.Visible = False
        _registrations.DBReadOnly = True
        _registrations.AvailableToClient = False
        Me.Fields.Add(_registrations)
        '
        '_currentregistrantindex
        '
        _currentregistrantindex.Name = "CURRENTREGISTRANTINDEX"
        _currentregistrantindex.Caption = "CURRENTREGISTRANTINDEX"
        _currentregistrantindex.Visible = False
        _currentregistrantindex.DBReadOnly = True
        _currentregistrantindex.AvailableToClient = False
        Me.Fields.Add(_currentregistrantindex)
        '
        '_startdate
        '
        _startdate.Name = "STARTDATE"
        _startdate.Caption = "Date"
        _startdate.DBReadOnly = True
        Me.Fields.Add(_startdate)
        '
        '_type
        '
        _type.Name = "TYPE"
        _type.Caption = "Type"
        _type.DBReadOnly = True
        Me.Fields.Add(_type)
        '
        '_status
        '
        _status.Name = "STATUS"
        _status.Caption = "Status"
        _status.DBReadOnly = True
        Me.Fields.Add(_status)
        '
        '_registration
        '
        _registration.Name = "REGISTRATION"
        _registration.Caption = "Registration"
        _registration.DBReadOnly = True
        Me.Fields.Add(_registration)
        '
        '_registrationcounttext
        '
        _registrationcounttext.Name = "REGISTRATIONCOUNTTEXT"
        _registrationcounttext.Caption = "REGISTRATIONCOUNTTEXT"
        _registrationcounttext.DBReadOnly = True
        Me.Fields.Add(_registrationcounttext)
        '
        '_currentregistrantid
        '
        _currentregistrantid.Name = "CURRENTREGISTRANTID"
        _currentregistrantid.Caption = "CURRENTREGISTRANTID"
        _currentregistrantid.Visible = False
        _currentregistrantid.DBReadOnly = True
        _currentregistrantid.AvailableToClient = False
        Me.Fields.Add(_currentregistrantid)
        '
        '_noregistrations
        '
        _noregistrations.Name = "NOREGISTRATIONS"
        _noregistrations.Caption = "No event registrations"
        _noregistrations.Visible = False
        _noregistrations.DBReadOnly = True
        Me.Fields.Add(_noregistrations)
        '
        '_headerlink
        '
        _headerlink.Name = "HEADERLINK"
        _headerlink.Caption = "Registrations"
        _headerlink.PageId = New System.Guid("88159265-2b7e-4c7b-82a2-119d01ecd40f")
        _headerlink.TabId = New System.Guid("886ad8d7-0304-4d75-aa55-b77d50e3bcce")
        _headerlink.ForceReload = False
        _headerlink.ContextIdDefinition = "FORM!CURRENTRECORDID"
        Me.Actions.Add(_headerlink)
        '
        '_eventname
        '
        _eventname.Name = "EVENTNAME"
        _eventname.Caption = "Event"
        _eventname.PageId = New System.Guid("83ce565e-4f03-40cf-9134-a226e4ba5b50")
        _eventname.ContextIdDefinition = "Fields!CURRENTREGISTRANTID"
        Me.Actions.Add(_eventname)
        '
        '_nextregistration
        '
        _nextregistration.Name = "NEXTREGISTRATION"
        _nextregistration.Caption = ""
        Me.Actions.Add(_nextregistration)
        '
        '_previousregistration
        '
        _previousregistration.Name = "PREVIOUSREGISTRATION"
        _previousregistration.Caption = ""
        Me.Actions.Add(_previousregistration)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [REGISTRATIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentSummaryEventRegistrationsTileViewFormREGISTRATIONSUIModel)
        Get
            Return _registrations
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [CURRENTREGISTRANTINDEX]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _currentregistrantindex
        End Get
    End Property
    
    ''' <summary>
    ''' Date
    ''' </summary>
    <System.ComponentModel.Description("Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [STARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _startdate
        End Get
    End Property
    
    ''' <summary>
    ''' Type
    ''' </summary>
    <System.ComponentModel.Description("Type")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [TYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _type
        End Get
    End Property
    
    ''' <summary>
    ''' Status
    ''' </summary>
    <System.ComponentModel.Description("Status")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [STATUS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _status
        End Get
    End Property
    
    ''' <summary>
    ''' Registration
    ''' </summary>
    <System.ComponentModel.Description("Registration")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [REGISTRATION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _registration
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [REGISTRATIONCOUNTTEXT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _registrationcounttext
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [CURRENTREGISTRANTID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _currentregistrantid
        End Get
    End Property
    
    ''' <summary>
    ''' No event registrations
    ''' </summary>
    <System.ComponentModel.Description("No event registrations")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [NOREGISTRATIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _noregistrations
        End Get
    End Property
    
    ''' <summary>
    ''' Registrations
    ''' </summary>
    <System.ComponentModel.Description("Registrations")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [HEADERLINK]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction
        Get
            Return _headerlink
        End Get
    End Property
    
    ''' <summary>
    ''' Event
    ''' </summary>
    <System.ComponentModel.Description("Event")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [EVENTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction
        Get
            Return _eventname
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [NEXTREGISTRATION]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _nextregistration
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [PREVIOUSREGISTRATION]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _previousregistration
        End Get
    End Property
    
End Class
