Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  3.16.460.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ConstituentSummaryEventRegistrationsTileViewFormREGISTRATIONS' data form
''' </summary>
Partial Public Class [ConstituentSummaryEventRegistrationsTileViewFormREGISTRATIONSUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the STATUSCODE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public Enum STATUSCODES As Integer
        [WillNotAttend] = 0
        [Registered] = 1
        [Cancelled] = 2
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _registrantid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _eventname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _startdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _iswalkin As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _statuscode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of STATUSCODES))
    Private WithEvents _registrationoptionname As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public Sub New()
        MyBase.New()

        _registrantid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _eventname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _startdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _iswalkin = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _statuscode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of STATUSCODES))
        _registrationoptionname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        '
        '_registrantid
        '
        _registrantid.Name = "REGISTRANTID"
        _registrantid.Caption = "REGISTRANTID"
        _registrantid.DBReadOnly = True
        Me.Fields.Add(_registrantid)
        '
        '_eventname
        '
        _eventname.Name = "EVENTNAME"
        _eventname.Caption = "EVENTNAME"
        _eventname.DBReadOnly = True
        Me.Fields.Add(_eventname)
        '
        '_startdate
        '
        _startdate.Name = "STARTDATE"
        _startdate.Caption = "STARTDATE"
        _startdate.DBReadOnly = True
        Me.Fields.Add(_startdate)
        '
        '_iswalkin
        '
        _iswalkin.Name = "ISWALKIN"
        _iswalkin.Caption = "ISWALKIN"
        _iswalkin.DBReadOnly = True
        Me.Fields.Add(_iswalkin)
        '
        '_statuscode
        '
        _statuscode.Name = "STATUSCODE"
        _statuscode.Caption = "STATUSCODE"
        _statuscode.DBReadOnly = True
        _statuscode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of STATUSCODES)) With {.Value = STATUSCODES.[WillNotAttend], .Translation = "Will not attend"})
        _statuscode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of STATUSCODES)) With {.Value = STATUSCODES.[Registered], .Translation = "Registered"})
        _statuscode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of STATUSCODES)) With {.Value = STATUSCODES.[Cancelled], .Translation = "Cancelled"})
        Me.Fields.Add(_statuscode)
        '
        '_registrationoptionname
        '
        _registrationoptionname.Name = "REGISTRATIONOPTIONNAME"
        _registrationoptionname.Caption = "REGISTRATIONOPTIONNAME"
        _registrationoptionname.DBReadOnly = True
        Me.Fields.Add(_registrationoptionname)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [REGISTRANTID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _registrantid
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [EVENTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _eventname
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [STARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _startdate
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [ISWALKIN]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _iswalkin
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [STATUSCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of STATUSCODES))
        Get
            Return _statuscode
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "3.16.460.0")> _
    Public ReadOnly Property [REGISTRATIONOPTIONNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _registrationoptionname
        End Get
    End Property
    
End Class
